version: '3.4'
services:
  php:
    working_dir: /var/www
    build:
      context: docker
      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      - veildb-network
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      PHP_IDE_CONFIG: serverName=docker
      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL: mysql://${DB_USERNAME}:${DB_PASSWORD}@database:3306/${DB_DATABASE}?serverVersion=8&charset=utf8mb4
    volumes:
      - "./src/backend:/var/www"
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  nginx:
    image: nginx:alpine
    depends_on:
      - php
    tty: true
    environment:
      PHP_IDE_CONFIG: serverName=docker
    ports:
      - ${NGINX_PORT}:80
    networks:
      - veildb-network
    volumes:
      - ./src/backend:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  frontend:
    image: node:20
    stdin_open: true
    working_dir: /frontend
    command: 'bash -c "yarn install && yarn build && yarn start"'
    volumes:
      - ./src/frontend:/frontend
      - /frontend/node_modules
    tty: true
    networks:
      - veildb-network

  database:
    image: mysql:8.0.22
    platform: linux/x86_64
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    networks:
      - veildb-network
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

networks:
  veildb-network:
    driver: bridge

volumes:
  veildb-dbdata:
    driver: local
